import re

with open('lib/i18n/translations.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# Remove corrupted footer entries first
content = re.sub(r"\s*'footer\.[^']*':\s*'[^']*',,(\n|$)", r"\1", content)

# Footer translations for each language
footers = {
    'en': {},  # English already has footers
    'hi': {
        'footer.product': 'उत्पाद',
        'footer.productFeatures': 'विशेषताएं',
        'footer.productHowItWorks': 'यह कैसे काम करता है',
        'footer.productTestimonials': 'प्रशंसापत्र',
        'footer.productFAQ': 'FAQ',
        'footer.company': 'कंपनी',
        'footer.companyAbout': 'परिचय',
        'footer.companyBlog': 'ब्लॉग',
        'footer.companyContact': 'संपर्क',
        'footer.legal': 'कानूनी',
        'footer.legalPrivacy': 'गोपनीयता',
        'footer.legalTerms': 'शर्तें',
        'footer.cookiePolicy': 'कुकी नीति',
        'footer.accessibility': 'अभिगम्यता',
        'footer.encryption': '256-बिट एन्क्रिप्शन',
        'footer.hipaa': 'HIPAA अनुपालन',
        'footer.wcag': 'WCAG 2.1 AA सुलभ',
    },
    'ta': {
        'footer.product': 'பொருட்கள்',
        'footer.productFeatures': 'அம்சங்கள்',
        'footer.productHowItWorks': 'இது எப்படி வேலை செய்கிறது',
        'footer.productTestimonials': 'சாட்சியங்கள்',
        'footer.productFAQ': 'FAQ',
        'footer.company': 'நிறுவனம்',
        'footer.companyAbout': 'பற்றி',
        'footer.companyBlog': 'வலைப்பூ',
        'footer.companyContact': 'தொடர்பு',
        'footer.legal': 'சட்ட',
        'footer.legalPrivacy': 'தனியுரிமை',
        'footer.legalTerms': 'நிபந்தனைகள்',
        'footer.cookiePolicy': 'குக்கி கொள்கை',
        'footer.accessibility': 'அணுகல்தன்மை',
        'footer.encryption': '256-பிட் குறியாக்கம்',
        'footer.hipaa': 'HIPAA இணங்கும்',
        'footer.wcag': 'WCAG 2.1 AA அணுகக்கூடியது',
    },
    'te': {
        'footer.product': 'ఉత్పత్తి',
        'footer.productFeatures': 'లక్షణాలు',
        'footer.productHowItWorks': 'ఇది ఎలా పనిచేస్తుంది',
        'footer.productTestimonials': 'సాక్ష్యాలు',
        'footer.productFAQ': 'FAQ',
        'footer.company': 'కంపెనీ',
        'footer.companyAbout': 'గురించి',
        'footer.companyBlog': 'బ్లాగ్',
        'footer.companyContact': 'సంపర్కించండి',
        'footer.legal': 'చట్టపరమైన',
        'footer.legalPrivacy': 'గోపనීయత',
        'footer.legalTerms': 'నిబంధనలు',
        'footer.cookiePolicy': 'కుకీ విధానం',
        'footer.accessibility': 'ఆక్సెసిబిలిటీ',
        'footer.encryption': '256-బిట్ ఎన్‌క్రిప్షన్',
        'footer.hipaa': 'HIPAA సమ్మతి',
        'footer.wcag': 'WCAG 2.1 AA ప్రాప్యమైనది',
    },
    'ml': {
        'footer.product': 'ഉൽപ്പാദനം',
        'footer.productFeatures': 'സവിശേഷതകൾ',
        'footer.productHowItWorks': 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
        'footer.productTestimonials': 'സാക്ഷ്യങ്ങൾ',
        'footer.productFAQ': 'FAQ',
        'footer.company': 'കമ്പനി',
        'footer.companyAbout': 'കുറിച്ച്',
        'footer.companyBlog': 'ബ്ലോഗ്',
        'footer.companyContact': 'ബന്ധപ്പെടുക',
        'footer.legal': 'നിയമപരം',
        'footer.legalPrivacy': 'സ്വകാര്യത',
        'footer.legalTerms': 'നിബന്ധനകൾ',
        'footer.cookiePolicy': 'കുക്കി നയം',
        'footer.accessibility': 'പ്രവേശനശീലത',
        'footer.encryption': '256-ബിറ്റ് എൻക്രിപ്ഷൻ',
        'footer.hipaa': 'HIPAA കമ്പ്ലയന്റ്',
        'footer.wcag': 'WCAG 2.1 AA ആക്സസ് ചെയ്യാവുന്നത്',
    },
    'bn': {
        'footer.product': 'পণ্য',
        'footer.productFeatures': 'বৈশিষ্ট্য',
        'footer.productHowItWorks': 'এটি কীভাবে কাজ করে',
        'footer.productTestimonials': 'সাক্ষ্য',
        'footer.productFAQ': 'FAQ',
        'footer.company': 'কোম্পানি',
        'footer.companyAbout': 'সম্পর্কে',
        'footer.companyBlog': 'ব্লগ',
        'footer.companyContact': 'যোগাযোগ',
        'footer.legal': 'আইনি',
        'footer.legalPrivacy': 'গোপনীয়তা',
        'footer.legalTerms': 'শর্তাবলী',
        'footer.cookiePolicy': 'কুকি নীতি',
        'footer.accessibility': 'অ্যাক্সেসযোগ্যতা',
        'footer.encryption': '256-বিট এনক্রিপশন',
        'footer.hipaa': 'HIPAA সম্মত',
        'footer.wcag': 'WCAG 2.1 AA অ্যাক্সেসযোগ্য',
    },
    'mr': {
        'footer.product': 'उत्पाद',
        'footer.productFeatures': 'वैशिष्ट्ये',
        'footer.productHowItWorks': 'हे कसे कार्य करते',
        'footer.productTestimonials': 'साक्ष्य',
        'footer.productFAQ': 'FAQ',
        'footer.company': 'कंपनी',
        'footer.companyAbout': 'बद्दल',
        'footer.companyBlog': 'ब्लॉग',
        'footer.companyContact': 'संपर्क',
        'footer.legal': 'कायदेशीर',
        'footer.legalPrivacy': 'गोपनीयता',
        'footer.legalTerms': 'अटी',
        'footer.cookiePolicy': 'कुकी धोरण',
        'footer.accessibility': 'अभिगम्यता',
        'footer.encryption': '256-बिट एन्क्रिप्शन',
        'footer.hipaa': 'HIPAA अनुरूप',
        'footer.wcag': 'WCAG 2.1 AA प्रवेशयोग्य',
    },
    'gu': {
        'footer.product': 'પણ્ય',
        'footer.productFeatures': 'લક્ષણો',
        'footer.productHowItWorks': 'તે કેવી રીતે કાર્ય કરે છે',
        'footer.productTestimonials': 'પ્રશંસાપત્ર',
        'footer.productFAQ': 'FAQ',
        'footer.company': 'કંપની',
        'footer.companyAbout': 'વિશે',
        'footer.companyBlog': 'બ્લોગ',
        'footer.companyContact': 'સંપર્ક',
        'footer.legal': 'કાનૂની',
        'footer.legalPrivacy': 'ગોપનીયતા',
        'footer.legalTerms': 'શરતો',
        'footer.cookiePolicy': 'કુકીનો નિયમ',
        'footer.accessibility': 'શોધક્ષમતા',
        'footer.encryption': '256-બિટ એનક્રિપટન',
        'footer.hipaa': 'HIPAA આધીન',
        'footer.wcag': 'WCAG 2.1 AA સુલભ',
    },
    'kn': {
        'footer.product': 'ಉತ್ಪನ್ನ',
        'footer.productFeatures': 'ವೈಶಿಷ್ಟ್ಯ',
        'footer.productHowItWorks': 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
        'footer.productTestimonials': 'ಸಾಕ್ಷ್ಯ',
        'footer.productFAQ': 'FAQ',
        'footer.company': 'ಕಂಪನಿ',
        'footer.companyAbout': 'ಕುರಿತು',
        'footer.companyBlog': 'ಬ್ಲಾಗ್',
        'footer.companyContact': 'ಸಂಪರ್ಕ',
        'footer.legal': 'ಕಾನೂನು',
        'footer.legalPrivacy': 'ಗೌಪ್ಯತೆ',
        'footer.legalTerms': 'ನಿಯಮ',
        'footer.cookiePolicy': 'ಕುಕೀ ನೀತಿ',
        'footer.accessibility': 'ಪ್ರವೇಶನೀಯತೆ',
        'footer.encryption': '256-ಬಿಟ್ ಎನ್‌ಕ್ರಿಪ್ಶನ್',
        'footer.hipaa': 'HIPAA ಅನುರೂಪ',
        'footer.wcag': 'WCAG 2.1 AA ಪ್ರವೇಶಿಸಬಹುದಾದ',
    },
    'pa': {
        'footer.product': 'ਉਤਪਾਦ',
        'footer.productFeatures': 'ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
        'footer.productHowItWorks': 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
        'footer.productTestimonials': 'ਸਾਖੀ',
        'footer.productFAQ': 'FAQ',
        'footer.company': 'ਕੰਪਨੀ',
        'footer.companyAbout': 'ਬਾਰੇ',
        'footer.companyBlog': 'ਬਲੌਗ',
        'footer.companyContact': 'ਸੰਪਰਕ',
        'footer.legal': 'ਕਾਨੂੰਨੀ',
        'footer.legalPrivacy': 'ਨਿਜਤਾ',
        'footer.legalTerms': 'ਸ਼ਰਤਾਂ',
        'footer.cookiePolicy': 'ਕੁਕੀ ਨੀਤੀ',
        'footer.accessibility': 'ਰਸਾਈ',
        'footer.encryption': '256-ਬਿੱਟ ਏਨਕ੍ਰਿਪਸ਼ਨ',
        'footer.hipaa': 'HIPAA ਅਨੁਕੂਲ',
        'footer.wcag': 'WCAG 2.1 AA ਪਹੁੰਚਯੋਗ',
    },
    'as': {
        'footer.product': 'পণ্য',
        'footer.productFeatures': 'বৈশিষ্ট্য',
        'footer.productHowItWorks': 'ই কেনেকৈ কাম কৰে',
        'footer.productTestimonials': 'সাক্ষ্য',
        'footer.productFAQ': 'FAQ',
        'footer.company': 'কোম্পানি',
        'footer.companyAbout': 'সম্পর্কে',
        'footer.companyBlog': 'ব্লগ',
        'footer.companyContact': 'যোগাযোগ',
        'footer.legal': 'আইনি',
        'footer.legalPrivacy': 'গোপনীয়তা',
        'footer.legalTerms': 'পদ',
        'footer.cookiePolicy': 'কুকি নীতি',
        'footer.accessibility': 'সুলভতা',
        'footer.encryption': '256-বিট এনক্রিপশন',
        'footer.hipaa': 'HIPAA সম্মত',
        'footer.wcag': 'WCAG 2.1 AA সুলভ',
    },
    'or': {
        'footer.product': 'ଉତ୍ପାଦ',
        'footer.productFeatures': 'ବୈଶିଷ୍ଟ୍ୟ',
        'footer.productHowItWorks': 'ଏହା କିପରି କାର୍ୟ୍ୟ କରେ',
        'footer.productTestimonials': 'ପ୍ରଶଂସାପତ୍ର',
        'footer.productFAQ': 'FAQ',
        'footer.company': 'କମ୍ପାନୀ',
        'footer.companyAbout': 'ବିଷୟରେ',
        'footer.companyBlog': 'ବ୍ଲଗ',
        'footer.companyContact': 'ଯୋଗାଯୋଗ',
        'footer.legal': 'ଆଇନି',
        'footer.legalPrivacy': 'ଗୋପନୀୟତା',
        'footer.legalTerms': 'ସର୍ତ୍ତାବଳୀ',
        'footer.cookiePolicy': 'କୁକିଜ ନୀତି',
        'footer.accessibility': 'ସୁଲଭତା',
        'footer.encryption': '256-ବିଟ ଏନକ୍ରିପଶନ',
        'footer.hipaa': 'HIPAA ଅନୁରୂପ',
        'footer.wcag': 'WCAG 2.1 AA ଆକ୍ସେସଯୋଗ୍ୟ',
    }
}

# Process each language to add footers
for lang_code in ['hi', 'ta', 'te', 'ml', 'bn', 'mr', 'gu', 'kn', 'pa', 'as', 'or']:
    if lang_code in footers and footers[lang_code]:
        # Build footer entries
        footer_entries = []
        for key, value in footers[lang_code].items():
            footer_entries.append(f"    '{key}': '{value}'")

        footer_text = ",\n".join(footer_entries)

        # Find this language block's testimonials.subtitle and add footer after
        # Use a pattern that matches the specific closure point
        pattern = rf"({lang_code}: {{.*?    'testimonials\.subtitle': '[^']*',)\n(\s*\}},)"
        replacement = rf"\1,\n{footer_text}\n\2"
        content = re.sub(pattern, replacement, content, flags=re.DOTALL, count=1)

# Write back
with open('lib/i18n/translations.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print("Footer translations fixed and added!")
